import { queryCollection } from "@nuxt/content/server";
import { joinURL } from "ufo";

/**
 * The GitHub profile README, written from the same content as the home page, prerendered to `/readme.md`.
 *
 * Only the text is fixed at build time: every card is an image served live by the `/readme/*` routes,
 * so the README on github.com/RedStar071 needs updating only when the bio or the projects change.
 */
export default defineEventHandler(async (event) => {
  const site = getSiteConfig(event);
  const config = useRuntimeConfig(event);
  const [page, projects] = await Promise.all([
    queryCollection(event, "index").first(),
    queryCollection(event, "projects").order("order", "ASC").all()
  ]);
  if (!page)
    throw createError({ statusCode: 500, statusMessage: "content/index.yml is missing" });

  const url = (path: string) => joinURL(site.url, path);
  const card = (path: string, alt: string, width?: number) =>
    `<img src="${url(path)}" alt="${alt}"${width ? ` width="${width}"` : ""} />`;

  const featured = projects.slice(0, 6).map((project) => {
    const link = project.url ?? project.repo;
    return `- [**${project.title}**](${link}): ${project.description.replace(/\.$/, "")} _(${project.role})_`;
  });

  const markdown = [
    `<!-- Generated by ${url("readme.md")} from the site's content; edit content/index.yml instead. -->`,
    "",
    `<div align="center">`,
    "",
    `# ${page.hero.greeting} ${site.name} 👋`,
    "",
    page.hero.bio,
    "",
    `[${new URL(site.url).host}](${site.url}) · [Last.fm](https://www.last.fm/user/${config.public.lastfmUsername}) · [RSS](${url("rss.xml")})`,
    "",
    `</div>`,
    "",
    `## ${page.about.title}`,
    "",
    ...page.about.items.map(item => `- ${item}`),
    "",
    `## ${page.listening.title}`,
    "",
    `<a href="${url("readme/listening")}">${card("readme/listening.svg", `What ${site.name} is listening to`)}</a>`,
    "",
    `## ${page.projects.title}`,
    "",
    ...featured,
    "",
    `## ${page.stack.title}`,
    "",
    card("readme/stack.svg", page.stack.items.map(item => item.label).join(", ")),
    "",
    "## github stats",
    "",
    `<a href="https://github.com/${config.public.githubUsername}">`,
    `  ${card("readme/stats.svg", `${site.name}'s GitHub stats`, 495)}`,
    `  ${card("readme/languages.svg", `${site.name}'s most used languages`, 495)}`,
    `</a>`,
    ""
  ].join("\n");

  setResponseHeader(event, "content-type", "text/markdown; charset=utf-8");
  return markdown;
});
