import { queryCollection } from "@nuxt/content/server";
import { joinURL } from "ufo";

const GITHUB_AVATAR_ID = "76824516";
const SPOTIFY_USER_ID = "d7idltb8rrr4oqk3izjefxd1d";

/** `icon-marquee.giann.dev` slugs for the stack labels in `content/index.yml`. */
const STACK_SLUGS: Record<string, string> = {
  "TypeScript": "ts",
  "Vue": "vue",
  "Nuxt": "nuxt",
  "Node.js": "nodejs",
  "discord.js": "discordjs",
  "Tailwind CSS": "tailwind",
  "Docker": "docker",
  "Kubernetes": "kubernetes",
  "PostgreSQL": "postgres",
  "Cloudflare": "cloudflare"
};

/**
 * The GitHub profile README, written from the same content as the home page, prerendered to `/readme.md`.
 *
 * Only the text is fixed at build time: the listening, stack and avatar cards are images served live by
 * third-party services and the stats cards by the `/readme/*` routes, so the README on github.com/RedStar071
 * needs updating only when the bio or the projects change.
 */
export default defineEventHandler(async (event) => {
  const site = getSiteConfig(event);
  const config = useRuntimeConfig(event);
  const [page, projects] = await Promise.all([
    queryCollection(event, "index").first(),
    queryCollection(event, "projects").order("order", "ASC").all()
  ]);
  if (!page)
    throw createError({ statusCode: 500, statusMessage: "content/index.yml is missing" });

  const url = (path: string) => joinURL(site.url, path);
  const card = (path: string, alt: string, width?: number) =>
    `<img src="${url(path)}" alt="${alt}"${width ? ` width="${width}"` : ""} />`;

  const featured = projects.slice(0, 6).map((project) => {
    const link = project.url ?? project.repo;
    return `- [**${project.title}**](${link}): ${project.description.replace(/\.$/, "")} _(${project.role})_`;
  });

  const stackLabels = page.stack.items.map(item => item.label);
  const stackSlugs = stackLabels.map((label) => {
    const slug = STACK_SLUGS[label];
    if (!slug)
      throw createError({ statusCode: 500, statusMessage: `No icon-marquee slug for "${label}"` });
    return slug;
  });

  const markdown = [
    `<!-- Generated by ${url("readme.md")} from the site's content; edit content/index.yml instead. -->`,
    "",
    `<div align="center">`,
    "",
    `<img height="150" src="https://avatars.githubusercontent.com/u/${GITHUB_AVATAR_ID}" alt="${config.public.githubUsername} avatar" />`,
    "",
    `# ${page.hero.greeting} ${site.name} 👋`,
    "",
    page.hero.bio,
    "",
    `[${new URL(site.url).host}](${site.url}) · [Last.fm](https://www.last.fm/user/${config.public.lastfmUsername}) · [RSS](${url("rss.xml")})`,
    "",
    `</div>`,
    "",
    `## ${page.about.title}`,
    "",
    ...page.about.items.map(item => `- ${item}`),
    "",
    `## ${page.listening.title}`,
    "",
    `<a href="https://open.spotify.com/user/${SPOTIFY_USER_ID}">`,
    `  <img src="https://spotify-recently-played-readme.vercel.app/api?user=${SPOTIFY_USER_ID}&count=5&unique=true" alt="Spotify recently played" />`,
    `</a>`,
    "",
    `## ${page.projects.title}`,
    "",
    ...featured,
    "",
    `## ${page.stack.title}`,
    "",
    `<img src="https://icon-marquee.giann.dev/v1/marquee?i=${stackSlugs.join(",")}&width=800" alt="${stackLabels.join(", ")}" />`,
    "",
    "## github stats",
    "",
    `<a href="https://github.com/${config.public.githubUsername}">`,
    `  ${card("readme/stats.svg", `${site.name}'s GitHub stats`, 495)}`,
    `  ${card("readme/languages.svg", `${site.name}'s most used languages`, 495)}`,
    `</a>`,
    ""
  ].join("\n");

  setResponseHeader(event, "content-type", "text/markdown; charset=utf-8");
  return markdown;
});
